title: "ICS Security Switzerland"
description: "Connecting experts in Switzerland to advance industrial cybersecurity and IEC 62443 adoption."
url: "https://www.icssec.ch"
baseurl: ""
lang: en-GB
timezone: Europe/Zurich

# theme: minima  # using custom layouts

header_pages:
  - about.md
  - members.md
  - contacts.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

permalink: /:categories/:title/
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: lsquo,rsquo,ldquo,rdquo

date_format: "%-d. %B %Y"
show_excerpts: true

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/og-image.png

exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - scripts
  - functions
